DROP TABLE F_STATEMENT;
CREATE TABLE F_STATEMENT(
cid			NUMBER,
memid		VARCHAR2(20),
price		NUMBER CONSTRAINTS f_statement_price_nn NOT NULL,
reg_date	TIMESTAMP DEFAULT SYSDATE,
CONSTRAINT f_statement_cid_fk FOREIGN KEY (cid) 
								 REFERENCES F_CLASS(cid),
CONSTRAINT f_statement_memid_fk FOREIGN KEY (memid) 
								 REFERENCES UU_MEMBER(memid)
);